scripts: oe-init-build-env: Add copyright, fix bugs, use by console

diff --git a/oe-init-build-env b/oe-init-build-env
--- a/oe-init-build-env
+++ b/oe-init-build-env
@@ -1,4 +1,13 @@
-#!/bin/bash
+#!/bin/sh
+
+# OE Build Environment Setup Script
+#
+# Copyright (C) 2006-2011 Linux Foundation
+# Copyright (C) 2020 Nathan Genetzky
+#
+# SPDX-License-Identifier: GPL-2.0-or-later
+#
+
 # Attempted to be as compatible with the 'oe-init-build-env' as possible.
 # WARNING: Unhandled use cases. poky/oe-init-build-env much more robust.
 #
@@ -10,7 +19,6 @@
 # - Configuration of 'bblayers' and 'local.conf' is done through kas.
 
 bitbake_set_path(){
-    local p
     p="$(readlink -f "${1?}")"
     if [ ! -d "${p}/bin/" ]; then
       return 1
@@ -20,9 +28,7 @@ bitbake_set_path(){
     export PYTHONPATH="${p}/lib:$PYTHONPATH"
 }
 
-oe_init_build_env(){
-    local d_build d_bitbake
-
+_oe_init_build_env(){
     if [ -z "${1-}" ]; then
         d_build="${BUILDDIR-build}"
     else
@@ -57,8 +63,33 @@ oe_init_build_env(){
     cd "${d_build}" || return 1
 }
 
-set -x
-oe_init_build_env "$@"
-set +x
+oe_init_build_env(){
+    # We are attempting to other shells besides bash
+    # shellcheck disable=SC2128
+    if [ -n "$BASH_SOURCE" ]; then
+        THIS_SCRIPT=$BASH_SOURCE
+    elif [ -n "$ZSH_NAME" ]; then
+        THIS_SCRIPT=$0
+    else
+        THIS_SCRIPT="$(pwd)/oe-init-build-env"
+        if [ ! -e "$THIS_SCRIPT" ]; then
+            echo "Error: $THIS_SCRIPT doesn't exist!" >&2
+            echo "Please run this script in oe-init-build-env's directory." >&2
+            return 1
+        fi
+    fi
 
-unset bitbake_set_path oe_init_build_env
+    BASEDIR="$(dirname "$(readlink -f "$THIS_SCRIPT")")"
+    if ! cd "${BASEDIR}" ; then
+        echo "Failed to cd into BASEDIR (${BASEDIR})" >&2
+        return 1
+    fi
+
+    _oe_init_build_env "$@"
+}
+
+oe_init_build_env "$@"
+unset \
+    _oe_init_build_env \
+    bitbake_set_path \
+    oe_init_build_env
